export const buildLeadPayload = (formData: any, override?: any) => {
  return {
    branch: formData.branch,
    enquiry_date: formData.enquiryDate,
    enquiry_time: formData.enquiryTime,
    method: formData.method,
    channel: formData.channel,
    enquired_by: formData.enquiredBy,
    for_whom: formData.forWhom,
    student_name: override?.student_name || formData.studentName,
    mobile_number: override?.mobile_number || formData.mobileNumber,
    area: formData.area,
    gender: formData.gender,
    age: formData.age ? parseInt(formData.age) : null,
    marital_status: formData.maritalStatus,
    profession: formData.profession,
    education: formData.education,
    school_college_job: formData.schoolCollegeJob,
    school_timing: formData.schoolTiming,
    contact_time: formData.contactTime,
    department: formData.department,
    course: Array.isArray(formData.course)
      ? formData.course.join(", ")
      : formData.course,
    preferred_timing: formData.preferredTiming,
    preferred_batch: formData.preferredBatch,
    lead_chances: formData.leadChances,
    lead_stage: formData.leadStage,
    action: formData.action,
    next_follow_date: formData.nextFollowDate || null,
    next_follow_time: formData.nextFollowTime || null,
    counsellor: formData.counsellor,
    remark: formData.remark,
  };
};